#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x268 (0x728 - 0x4C0)
// WidgetBlueprintGeneratedClass FriendsList.FriendsList_C
class UFriendsList_C : public UFriendsList
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x4C0(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class UW_Button_C*                           btn_Expand;                                        // 0x4C8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                         Div_Away;                                          // 0x4D0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                         Div_Joinable;                                      // 0x4D8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                         Div_Online;                                        // 0x4E0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Icn_Expand_Left;                                   // 0x4E8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                         NoJoinable;                                        // 0x4F0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                         OfflineWarning;                                    // 0x4F8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                            ScrollBox_0;                                       // 0x500(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                          VB_Away;                                           // 0x508(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                          VB_HIDDEN;                                         // 0x510(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                          VB_Joinable;                                       // 0x518(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                          VB_Online;                                         // 0x520(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	double                                       LastScrolloffset;                                  // 0x528(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_            FriendsListUpdated;                                // 0x530(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMap<class FString, class UW_FriendsList_Entry_C*> FriendEntryMap;                                    // 0x540(0x50)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	bool                                         DebugMode;                                         // 0x590(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         Is_Design_Time;                                    // 0x591(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         Minimized;                                         // 0x592(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         UseGamepad;                                        // 0x593(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_360A[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TSet<class UW_FriendsList_Entry_C*>          JoinableEntries;                                   // 0x598(0x50)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TSet<class UW_FriendsList_Entry_C*>          OnlineEntries;                                     // 0x5E8(0x50)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TSet<class UW_FriendsList_Entry_C*>          AwayEntries;                                       // 0x638(0x50)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	int32                                        CurrentNavIndex;                                   // 0x688(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_3620[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	FMulticastInlineDelegateProperty_            ViewableProfileHovered;                            // 0x690(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_            NonViewableProfileHovered;                         // 0x6A0(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	int32                                        DebugEntryCount;                                   // 0x6B0(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_3631[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class UW_FriendsList_Entry_C*                CurrentNavFocus;                                   // 0x6B8(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TMap<class FString, class UW_FriendsList_Entry_C*> HiddenEntryMap;                                    // 0x6C0(0x50)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	bool                                         Offline;                                           // 0x710(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_3644[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	FMulticastInlineDelegateProperty_            ConnectionStatusUpdated;                           // 0x718(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

	static class UClass* StaticClass();
	static class UFriendsList_C* GetDefaultObj();

	void GetFocusTarget(class UWidget** Focus, bool CallFunc_IsValid_ReturnValue, TArray<class UW_FriendsList_Entry_C*>& CallFunc_WidgetGetChildrenOfClass_ChildWidgets, class UW_FriendsList_Entry_C* CallFunc_Array_Get_Item, bool CallFunc_Array_IsValidIndex_ReturnValue);
	void BackPage(bool* Handled);
	void ConnectionStatusChanged(bool MultiplayerConnectionAvailable, bool Temp_bool_Variable, bool CallFunc_Not_PreBool_ReturnValue, const class FString& Temp_string_Variable, const class FString& Temp_string_Variable_1, bool CallFunc_Not_PreBool_ReturnValue_1, const class FString& K2Node_Select_Default, const class FString& CallFunc_Concat_StrStr_ReturnValue);
	void SortAllLists();
	void SortEntryList(class UWidget* ListContainer, const TArray<class FString>& DisplayNames, TMap<class FString, class UW_FriendsList_Entry_C*> NamesMap, int32 Temp_int_Array_Index_Variable, TArray<class UW_FriendsList_Entry_C*>& CallFunc_WidgetGetChildrenOfClass_ChildWidgets, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Array_IsValidIndex_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, class UW_FriendsList_Entry_C* CallFunc_Array_Get_Item, const class FString& CallFunc_GetDisplayName_Display_Name, const class FString& CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, class UW_FriendsList_Entry_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, class UPanelSlot* CallFunc_InsertChildAt_ReturnValue, TArray<class FString>& CallFunc_Map_Keys_Keys, int32 Temp_int_Loop_Counter_Variable_1, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_1);
	void UnhideEntry(class UW_FriendsList_Entry_C* FriendEntry, bool CallFunc_Map_Remove_ReturnValue, class UW_FriendsList_Entry_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void RemoveFriendEntry(class UW_FriendsList_Entry_C* Entry, bool HideEntry, class UWidget* NewFocus, const class FString& CallFunc_GetUniqueNetID_Unique_Net_Id_Str, class UVerticalBoxSlot* CallFunc_AddChildToVerticalBox_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, class UWidget* CallFunc_DoCustomNavigation_ReturnValue, const class FString& CallFunc_GetUniqueNetID_Unique_Net_Id_Str_1, class UWidget* CallFunc_DoCustomNavigation_ReturnValue_1, bool CallFunc_Map_Remove_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1);
	void UpdateNoJoinVisibility(bool Temp_bool_Variable, enum class ESlateVisibility Temp_byte_Variable, enum class ESlateVisibility Temp_byte_Variable_1, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_HasAnyChildren_ReturnValue, enum class ESlateVisibility K2Node_Select_Default);
	class UWidget* DoCustomNavigation(enum class EUINavigation Navigation, class UW_FriendsList_Entry_C* NavEntry, const TArray<class UW_FriendsList_Entry_C*>& Entries, int32 Temp_int_Variable, int32 Temp_int_Variable_1, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Array_Find_ReturnValue, class UW_FriendsList_Entry_C* CallFunc_Array_Get_Item, int32 CallFunc_Array_LastIndex_ReturnValue, class UW_FriendsList_Entry_C* CallFunc_Array_Get_Item_1, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_GreaterEqual_IntInt_ReturnValue, class UW_FriendsList_Entry_C* CallFunc_Array_Get_Item_2, bool K2Node_SwitchEnum_CmpSuccess, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, TArray<class UW_FriendsList_Entry_C*>& CallFunc_WidgetGetChildrenOfClass_ChildWidgets);
	void ToggleExpand();
	void UpdateStyle(bool Temp_bool_Variable, enum class ESlateVisibility Temp_byte_Variable, enum class ESlateVisibility Temp_byte_Variable_1, enum class ESlateVisibility K2Node_Select_Default);
	void RefreshDebugFriends(const struct FFriend& RefreshFriend, bool InGame, class UW_FriendsList_Entry_C* DebugF, int32 StatusState, bool Joinable, const struct FFriend& DebugFriendData, class UW_FriendsList_Entry_C* DebugFriendEntry, int32 Temp_int_Variable, const class FString& Temp_string_Variable, const class FString& Temp_string_Variable_1, const class FString& Temp_string_Variable_2, const class FString& Temp_string_Variable_3, const class FString& Temp_string_Variable_4, int32 Temp_int_Array_Index_Variable, int32 CallFunc_Array_Add_ReturnValue, const struct FFriend& CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Array_RemoveItem_ReturnValue, bool CallFunc_RandomBoolWithWeight_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_RandomIntegerInRange_ReturnValue, bool CallFunc_RandomBoolWithWeight_ReturnValue_1, const class FString& K2Node_Select_Default, TArray<class UW_FriendsList_Entry_C*>& CallFunc_Map_Values_Values, const class FString& CallFunc_SelectString_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue);
	void PlaceFriendEntryByState(class UW_FriendsList_Entry_C* FriendEntry, bool Temp_bool_Variable, bool CallFunc_GreaterEqual_IntInt_ReturnValue, bool Temp_bool_Variable_1, class UPanelWidget* K2Node_Select_Default, class UPanelWidget* K2Node_Select_Default_1, class UPanelSlot* CallFunc_AddChild_ReturnValue, bool CallFunc_HasChild_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue);
	void MaximizeList(bool Temp_bool_Variable, enum class ESlateVisibility Temp_byte_Variable, enum class ESlateVisibility Temp_byte_Variable_1, bool Temp_bool_Variable_1, enum class ESlateVisibility Temp_byte_Variable_2, enum class ESlateVisibility Temp_byte_Variable_3, bool Temp_bool_Variable_2, enum class ESlateVisibility Temp_byte_Variable_4, enum class ESlateVisibility Temp_byte_Variable_5, bool CallFunc_IsValid_ReturnValue, TArray<class UW_FriendsList_Entry_C*>& CallFunc_WidgetGetChildrenOfClass_ChildWidgets, class UW_FriendsList_Entry_C* CallFunc_Array_Get_Item, bool CallFunc_Array_IsValidIndex_ReturnValue, bool CallFunc_HasAnyChildren_ReturnValue, bool CallFunc_HasAnyChildren_ReturnValue_1, enum class ESlateVisibility K2Node_Select_Default, enum class ESlateVisibility K2Node_Select_Default_1, bool CallFunc_HasAnyChildren_ReturnValue_2, enum class ESlateVisibility K2Node_Select_Default_2);
	void MinimizeList();
	void GenerateDebugFriendData(int32 Index, struct FFriend* DebugFriend, int32 StatusState, bool Joinable, int32 Temp_int_Variable, int64 CallFunc_Conv_IntToInt64_ReturnValue, const class FString& CallFunc_Conv_IntToString_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, const class FString& Temp_string_Variable, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Format_ReturnValue, const class FString& Temp_string_Variable_1, const class FString& CallFunc_Conv_TextToString_ReturnValue, const class FString& Temp_string_Variable_2, const class FString& Temp_string_Variable_3, const class FString& Temp_string_Variable_4, const class FString& K2Node_Select_Default, const class FString& CallFunc_SelectString_ReturnValue, int32 CallFunc_RandomIntegerInRange_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue, const struct FFriend& K2Node_MakeStruct_Friend, bool CallFunc_RandomBoolWithWeight_ReturnValue);
	void PopulateDebugFriends(const struct FFriend& DebugFriendData, class UW_FriendsList_Entry_C* DebugFriendEntry, const struct FTimerHandle& CallFunc_K2_SetTimer_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, int32 Temp_int_Variable, bool CallFunc_BooleanOR_ReturnValue, const struct FFriend& CallFunc_GenerateDebugFriendData_DebugFriend, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
	void CreateFriendEntry(const struct FFriend& Friend, class UW_FriendsList_Entry_C** NewEntryWidget, class UW_FriendsList_Entry_C* EntryWidget, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_2, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class UW_FriendsList_Entry_C* CallFunc_Create_ReturnValue);
	void UpdateFriendsList(const struct FFriend& CurrentFriend, class UW_FriendsList_Entry_C* Temp_wildcard_Variable, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UW_FriendsList_Entry_C* Temp_wildcard_Variable_1, bool CallFunc_IsValid_ReturnValue_2, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, bool CallFunc_Not_PreBool_ReturnValue, TArray<class UW_FriendsList_Entry_C*>& CallFunc_WidgetGetChildrenOfClass_ChildWidgets, class UW_FriendsList_Entry_C* CallFunc_Array_Get_Item, bool CallFunc_Array_IsValidIndex_ReturnValue, class UW_FriendsList_Entry_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, class UW_FriendsList_Entry_C* CallFunc_CreateFriendEntry_NewEntryWidget, class UW_FriendsList_Entry_C* CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1, class UW_FriendsList_Entry_C* CallFunc_Map_Find_Value_2, bool CallFunc_Map_Find_ReturnValue_2, class UW_FriendsList_Entry_C* CallFunc_Map_Find_Value_3, bool CallFunc_Map_Find_ReturnValue_3, int32 CallFunc_GetNumberOfFriends_Count, const struct FFriend& CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, float CallFunc_SetScrollOffset_NewScrollOffset_ImplicitCast);
	void GetNumberOfFriends(int32* Count, int32 CallFunc_Map_Length_ReturnValue);
	class UWidget* BP_GetDesiredFocusTarget(const TArray<class UWidget*>& ValidEntries, class UWidget* CallFunc_GetFocusTarget_Focus);
	void RemoveNonExistentFriendWidgets(const TArray<class FString>& FriendIDs, class UWidget* NewFocus, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, const struct FFriend& CallFunc_Array_Get_Item, TArray<class UW_FriendsList_Entry_C*>& CallFunc_Map_Values_Values, class UW_FriendsList_Entry_C* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Add_ReturnValue, const class FString& CallFunc_GetUniqueNetID_Unique_Net_Id_Str, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Array_Contains_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_1, bool CallFunc_Not_PreBool_ReturnValue);
	void DoesFriendExistAlready(const struct FFriend& TestFriend, bool* Exists_, class UW_FriendsList_Entry_C** FriendEntry, bool FriendExist_, class UW_FriendsList_Entry_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	enum class ESlateVisibility GetNoFriendsPlayingText(bool AnyVisible, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<class UW_FriendsList_Entry_C*>& CallFunc_Map_Values_Values, class UW_FriendsList_Entry_C* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, enum class ESlateVisibility CallFunc_GetVisibility_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess);
	void Reveal(double Delay);
	void Hide(double Delay, bool Collapse);
	void SetInputMode(bool IsGamepad);
	void ChangePage(class FName PageName);
	void OnSuccess_Event_0();
	void OnFailure_Event_0();
	void PreConstruct(bool IsDesignTime);
	void BP_OnActivated();
	void OnJoinFriendClicked(class UW_FriendsList_Entry_C* TriggeringEntry, const struct FFriend& Friend);
	void BndEvt__FriendsList_btn_Expand_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature(class UW_Button_C* Button);
	void OnInitialized();
	void InputTypeChanged(enum class ECommonInputType bNewInputType);
	void OnViewProfileClicked(class UW_FriendsList_Entry_C* TriggeringEntry, const struct FFriend& Friend);
	void OnEntryHovered(class UW_FriendsList_Entry_C* TriggeringEntry, const struct FFriend& Friend);
	void OnConnectionStatusChanged(bool bIsMultiplayerConnectionAvailable);
	void ExecuteUbergraph_FriendsList(int32 EntryPoint, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, double K2Node_Event_Delay_1, double K2Node_Event_Delay, bool K2Node_Event_Collapse, bool K2Node_Event_IsGamepad, class FName K2Node_Event_PageName, bool K2Node_Event_IsDesignTime, float CallFunc_GetScrollOffset_ReturnValue, class UW_FriendsList_Entry_C* K2Node_CustomEvent_TriggeringEntry_2, const struct FFriend& K2Node_CustomEvent_Friend_2, class UW_Button_C* K2Node_ComponentBoundEvent_Button, class AReadyOrNotPlayerController* CallFunc_GetReadyOrNotPlayerController_ReturnValue, class UCommonInputSubsystem* CallFunc_GetLocalPlayerSubSystemFromPlayerController_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, enum class ECommonInputType CallFunc_GetCurrentInputType_ReturnValue, enum class ECommonInputType K2Node_CustomEvent_bNewInputType, bool CallFunc_EqualEqual_ByteByte_ReturnValue, class UCommonInputSubsystem* CallFunc_GetLocalPlayerSubsystem_ReturnValue, TArray<class UW_FriendsList_Entry_C*>& CallFunc_Map_Values_Values, class UW_FriendsList_Entry_C* CallFunc_Array_Get_Item, bool CallFunc_Not_PreBool_ReturnValue, TScriptInterface<class IReadyOrNotUI_C> CallFunc_SetInputMode_self_CastInput, bool CallFunc_BooleanAND_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class UW_FriendsList_Entry_C* K2Node_CustomEvent_TriggeringEntry_1, const struct FFriend& K2Node_CustomEvent_Friend_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, bool CallFunc_ShowProfileUI_ReturnValue, class UW_FriendsList_Entry_C* K2Node_CustomEvent_TriggeringEntry, const struct FFriend& K2Node_CustomEvent_Friend, bool CallFunc_IsLocalPlatformUser_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_Not_PreBool_ReturnValue_2, bool K2Node_Event_bIsMultiplayerConnectionAvailable, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_2, double K2Node_VariableSet_LastScrolloffset_ImplicitCast);
	void ConnectionStatusUpdated__DelegateSignature(bool Offline);
	void NonViewableProfileHovered__DelegateSignature(const struct FFriend& Friend);
	void ViewableProfileHovered__DelegateSignature(const struct FFriend& Friend);
	void FriendsListUpdated__DelegateSignature(int32 Number_of_Friends);
};

}


