#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x138 (0x548 - 0x410)
// WidgetBlueprintGeneratedClass W_Credits.W_Credits_C
class UW_Credits_C : public UCommonActivatableWidget
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x410(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                      AnimFadeBackground;                                // 0x418(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                Background;                                        // 0x420(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                          CanvasPanel_0;                                     // 0x428(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                            ScrollBox_15;                                      // 0x430(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUniformGridPanel*                     UniformGridPanel_93;                               // 0x438(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_ScreenFooter_C*                     W_ScreenFooter;                                    // 0x440(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDataTable*                            CreditsDataTable;                                  // 0x448(0x8)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class UBaseCredit*>                   Credits;                                           // 0x450(0x10)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	struct FMargin                               DisplayMargins;                                    // 0x460(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	double                                       CreditSpacing;                                     // 0x470(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                       CreditScrollSpeed;                                 // 0x478(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                       ScrollboxHeight;                                   // 0x480(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FMargin                               CreditPadding;                                     // 0x488(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                         IsHeader;                                          // 0x498(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_382A[0x3];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	struct FMargin                               HeaderPadding;                                     // 0x49C(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                        Pad_382C[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TArray<class UW_SupporterCredit_C*>          SupporterCredits;                                  // 0x4B0(0x10)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class FText                                  Text1;                                             // 0x4C0(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                  Text2;                                             // 0x4D8(0x18)(Edit, BlueprintVisible, DisableEditOnInstance)
	FMulticastInlineDelegateProperty_            OnCreditsCompleted;                                // 0x4F0(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	double                                       AnimationPlaybackSpeed;                            // 0x500(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                        NextFadeInScrollDownIndex;                         // 0x508(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                        NextFadeInScrollUpIndex;                           // 0x50C(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         bFadeOutOnEnd;                                     // 0x510(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_383B[0x3];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	int32                                        NextFadeOutScrollDownIndex;                        // 0x514(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         bScrollingDown;                                    // 0x518(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_3842[0x3];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	int32                                        NextFadeOutScrollUpIndex;                          // 0x51C(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                             LocalCoordinate;                                   // 0x520(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                       MarginSize;                                        // 0x530(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                       Visible_Min;                                       // 0x538(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                       Visible_Max;                                       // 0x540(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class UW_Credits_C* GetDefaultObj();

	void OnScrollDirectionChanged(bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, int32 CallFunc_Max_ReturnValue, int32 CallFunc_Max_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue_2, bool CallFunc_Greater_IntInt_ReturnValue_3, int32 CallFunc_Subtract_IntInt_ReturnValue_2, int32 CallFunc_Subtract_IntInt_ReturnValue_3, int32 CallFunc_Max_ReturnValue_2, int32 CallFunc_Max_ReturnValue_3, int32 Temp_int_Variable, class UBaseCredit* CallFunc_Array_Get_Item, bool CallFunc_IsPlayingAnimation_ReturnValue, int32 Temp_int_Variable_1, int32 Temp_int_Variable_2, class UBaseCredit* CallFunc_Array_Get_Item_1, bool CallFunc_IsPlayingAnimation_ReturnValue_1, int32 Temp_int_Variable_3, class UBaseCredit* CallFunc_Array_Get_Item_2, bool CallFunc_IsPlayingAnimation_ReturnValue_2, class UBaseCredit* CallFunc_Array_Get_Item_3, bool CallFunc_IsPlayingAnimation_ReturnValue_3);
	void IsCreditInScrollBoxMargin(class UWidget* Credit, bool* IsInMargin, const struct FGeometry& CallFunc_GetTickSpaceGeometry_ReturnValue, double CallFunc_GetScrollboxDimensions_Height, double CallFunc_GetScrollboxDimensions_TopMargin, double CallFunc_GetScrollboxDimensions_BottomMargin, const struct FVector2D& CallFunc_LocalToViewport_PixelPosition, const struct FVector2D& CallFunc_LocalToViewport_ViewportPosition, double CallFunc_Subtract_DoubleDouble_ReturnValue, double CallFunc_BreakVector2D_X, double CallFunc_BreakVector2D_Y, bool CallFunc_GreaterEqual_DoubleDouble_ReturnValue, double CallFunc_GetScrollboxDimensions_Height_1, double CallFunc_GetScrollboxDimensions_TopMargin_1, double CallFunc_GetScrollboxDimensions_BottomMargin_1, double CallFunc_Add_DoubleDouble_ReturnValue, bool CallFunc_LessEqual_DoubleDouble_ReturnValue);
	void IsCreditInView(class UWidget* Credit, bool* IsInView, const struct FGeometry& CallFunc_GetTickSpaceGeometry_ReturnValue, const struct FVector2D& CallFunc_LocalToViewport_PixelPosition, const struct FVector2D& CallFunc_LocalToViewport_ViewportPosition, double CallFunc_GetScrollboxDimensions_Height, double CallFunc_GetScrollboxDimensions_TopMargin, double CallFunc_GetScrollboxDimensions_BottomMargin, double CallFunc_BreakVector2D_X, double CallFunc_BreakVector2D_Y, double CallFunc_Subtract_DoubleDouble_ReturnValue, double CallFunc_Add_DoubleDouble_ReturnValue, bool CallFunc_InRange_FloatFloat_ReturnValue);
	bool ShouldAnimateCredits(class UWidget* Credit, bool IsFadeIn, class UWidget* InCredit, bool CallFunc_IsCreditInView_IsInView, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_IsCreditInView_IsInView_1);
	void TriggerNextFadeOut(TArray<class UBaseCredit*>& Credits, class UBaseCredit* NextCredit, int32 Temp_int_Variable, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, TScriptInterface<class IReadyOrNotUI_C> K2Node_DynamicCast_AsReady_or_Not_UI, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue, bool CallFunc_ShouldAnimateCredits_ReturnValue, int32 Temp_int_Variable_1, bool CallFunc_BooleanAND_ReturnValue, int32 CallFunc_Max_ReturnValue, class UBaseCredit* CallFunc_Array_Get_Item, int32 CallFunc_Max_ReturnValue_1, class UBaseCredit* CallFunc_Array_Get_Item_1, int32 CallFunc_Add_IntInt_ReturnValue);
	void TriggerNextFadeIn(TArray<class UBaseCredit*>& Credits, class UBaseCredit* NextCredit, int32 Temp_int_Variable, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 Temp_int_Variable_1, int32 CallFunc_Max_ReturnValue, TScriptInterface<class IReadyOrNotUI_C> K2Node_DynamicCast_AsReady_or_Not_UI, bool K2Node_DynamicCast_bSuccess, class UBaseCredit* CallFunc_Array_Get_Item, bool CallFunc_IsValid_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_ShouldAnimateCredits_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, int32 CallFunc_Max_ReturnValue_1, class UBaseCredit* CallFunc_Array_Get_Item_1, int32 CallFunc_Add_IntInt_ReturnValue);
	struct FEventReply OnAnalogValueChanged(const struct FGeometry& MyGeometry, const struct FAnalogInputEvent& InAnalogInputEvent, bool ThumbstickYAxisChanged, float AnalogValue, double ScrollSpeedFactor, float CallFunc_GetAnalogValue_ReturnValue, const struct FKeyEvent& CallFunc_GetKeyEventFromAnalogInputEvent_ReturnValue, float CallFunc_NegateFloat_ReturnValue, const struct FKey& CallFunc_GetKey_ReturnValue, bool CallFunc_EqualEqual_KeyKey_ReturnValue, float CallFunc_GetGamepadMovementInnerDeadzone_GamepadMovementInnerDeadzone, bool CallFunc_GetGamepadMovementInnerDeadzone_ReturnValue, float CallFunc_GetGamepadMovementInnerDeadzone_GamepadMovementInnerDeadzone_1, bool CallFunc_GetGamepadMovementInnerDeadzone_ReturnValue_1, float CallFunc_NegateFloat_ReturnValue_1, bool CallFunc_InRange_FloatFloat_ReturnValue, double CallFunc_Add_DoubleDouble_ReturnValue, const struct FEventReply& CallFunc_Unhandled_ReturnValue, bool CallFunc_InRange_FloatFloat_ReturnValue_1, double CallFunc_Multiply_DoubleDouble_ReturnValue, const struct FEventReply& CallFunc_Handled_ReturnValue, double CallFunc_InRange_FloatFloat_Value_ImplicitCast, double CallFunc_InRange_FloatFloat_Max_ImplicitCast, double CallFunc_InRange_FloatFloat_Min_ImplicitCast, double CallFunc_InRange_FloatFloat_Min_ImplicitCast_1, double CallFunc_Add_DoubleDouble_A_ImplicitCast, double CallFunc_InRange_FloatFloat_Value_ImplicitCast_1, double CallFunc_Multiply_DoubleDouble_A_ImplicitCast);
	class UWidget* BP_GetDesiredFocusTarget();
	struct FEventReply OnKeyUp(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent, const struct FKey& CallFunc_GetKey_ReturnValue, const struct FEventReply& CallFunc_Unhandled_ReturnValue, bool CallFunc_EqualEqual_KeyKey_ReturnValue, bool CallFunc_EqualEqual_KeyKey_ReturnValue_1, const struct FEventReply& CallFunc_Handled_ReturnValue, bool CallFunc_BooleanOR_ReturnValue);
	struct FEventReply OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent, const struct FKey& CallFunc_GetKey_ReturnValue, bool CallFunc_EqualEqual_KeyKey_ReturnValue, bool CallFunc_EqualEqual_KeyKey_ReturnValue_1, const struct FEventReply& CallFunc_Unhandled_ReturnValue, const struct FEventReply& CallFunc_Handled_ReturnValue);
	void Update_Scroll_And_Animation_Speed(double Multiplier, double CallFunc_Multiply_DoubleDouble_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_NotEqual_DoubleDouble_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 CallFunc_Array_Length_ReturnValue, class UBaseCredit* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class UW_SupporterCredit_C* K2Node_DynamicCast_AsW_Supporter_Credit, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsAnimating_Animating, class UW_Credit_C* K2Node_DynamicCast_AsW_Credit, bool K2Node_DynamicCast_bSuccess_1, class UWidgetAnimation* CallFunc_WhichAnimation_Animation, bool CallFunc_IsAnimating_Animating_1, float K2Node_VariableSet_fAnimationSpeed_ImplicitCast, float K2Node_VariableSet_fAnimationSpeed_ImplicitCast_1, float CallFunc_SetPlaybackSpeed_PlaybackSpeed_ImplicitCast, float CallFunc_SetPlaybackSpeed_PlaybackSpeed_ImplicitCast_1);
	bool BP_OnHandleBackAction();
	void GetSupporterCredits(TArray<class FText>& SupporterCredits, TArray<class UW_SupporterCredit_C*>* SupporterCredit, int32 ArrayIndex, class UW_SupporterCredit_C* CallFunc_Create_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_Array_IsValidIndex_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_2, bool CallFunc_Array_IsValidIndex_ReturnValue_1);
	void RevealSupporterCredits(class UW_SupporterCredit_C* InputPin, int32 CallFunc_GetChildrenCount_ReturnValue, class UUniformGridSlot* CallFunc_AddChildToUniformGrid_ReturnValue, int32 CallFunc_Array_Add_ReturnValue);
	void RevealHeader(class UW_Credit_C* InputPin, int32 CallFunc_GetChildrenCount_ReturnValue, class UUniformGridSlot* CallFunc_AddChildToUniformGrid_ReturnValue, int32 CallFunc_Array_Add_ReturnValue);
	void RevealCredits(class UW_Credit_C* InputPin, int32 CallFunc_GetChildrenCount_ReturnValue, class UUniformGridSlot* CallFunc_AddChildToUniformGrid_ReturnValue, int32 CallFunc_Array_Add_ReturnValue);
	void Add_Spacer(int32 AmountOfSpacers, int32 Temp_int_Variable, int32 CallFunc_GetChildrenCount_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, class USpacer* CallFunc_SpawnObject_ReturnValue, class UUniformGridSlot* CallFunc_AddChildToUniformGrid_ReturnValue);
	void GetScrollboxDimensions(double* Height, double* TopMargin, double* BottomMargin, const struct FVector2D& CallFunc_GetViewportSize_ReturnValue, class UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue, double CallFunc_BreakVector2D_X, double CallFunc_BreakVector2D_Y, const struct FAnchors& CallFunc_GetAnchors_ReturnValue, double CallFunc_BreakVector2D_X_1, double CallFunc_BreakVector2D_Y_1, double CallFunc_BreakVector2D_X_2, double CallFunc_BreakVector2D_Y_2, double CallFunc_Multiply_DoubleDouble_ReturnValue, double CallFunc_Multiply_DoubleDouble_ReturnValue_1, double CallFunc_Subtract_DoubleDouble_ReturnValue, double CallFunc_Multiply_DoubleDouble_ReturnValue_2, double CallFunc_Add_DoubleDouble_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue_1);
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void BP_OnActivated();
	void End_Credits();
	void ExecuteUbergraph_W_Credits(int32 EntryPoint, class UW_Credit_C* CallFunc_Create_ReturnValue, bool K2Node_Event_IsDesignTime, const struct FGeometry& K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime, class UW_Credit_C* CallFunc_Create_ReturnValue_1, TArray<class FName>& CallFunc_GetDataTableRowNames_OutRowNames, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_GreaterEqual_DoubleDouble_ReturnValue, double CallFunc_Multiply_DoubleDouble_ReturnValue, double CallFunc_GetScrollboxDimensions_Height, double CallFunc_GetScrollboxDimensions_TopMargin, double CallFunc_GetScrollboxDimensions_BottomMargin, int32 Temp_int_Loop_Counter_Variable, class UW_Credit_C* CallFunc_Create_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue, class UUMGSequencePlayer* CallFunc_PlayAnimationForward_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class UUMGSequencePlayer* CallFunc_PlayAnimationReverse_ReturnValue, bool CallFunc_IsAnimationPlaying_ReturnValue, float CallFunc_GetScrollOffset_ReturnValue, double CallFunc_Add_DoubleDouble_ReturnValue, float CallFunc_GetScrollOffset_ReturnValue_1, float CallFunc_GetScrollOffsetOfEnd_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue, bool CallFunc_Less_DoubleDouble_ReturnValue, class UW_Credit_C* CallFunc_Create_ReturnValue_3, double CallFunc_GetScrollboxDimensions_Height_1, double CallFunc_GetScrollboxDimensions_TopMargin_1, double CallFunc_GetScrollboxDimensions_BottomMargin_1, double CallFunc_Add_DoubleDouble_ReturnValue_1, double CallFunc_Subtract_DoubleDouble_ReturnValue_1, class UW_Credit_C* CallFunc_Create_ReturnValue_4, int32 Temp_int_Array_Index_Variable, class FName CallFunc_Array_Get_Item, const struct FST_Credit& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, TArray<class UW_SupporterCredit_C*>& CallFunc_GetSupporterCredits_SupporterCredit, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_TextIsNotEmpty_NotEmpty, bool CallFunc_TextIsNotEmpty_NotEmpty_1, bool CallFunc_TextIsNotEmpty_NotEmpty_2, bool CallFunc_TextIsNotEmpty_NotEmpty_3, double CallFunc_Multiply_DoubleDouble_A_ImplicitCast, double CallFunc_Add_DoubleDouble_B_ImplicitCast, float CallFunc_SetScrollOffset_NewScrollOffset_ImplicitCast, double CallFunc_Subtract_DoubleDouble_B_ImplicitCast, double CallFunc_Subtract_DoubleDouble_A_ImplicitCast);
	void OnCreditsCompleted__DelegateSignature();
};

}


