#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0xE1 (0x511 - 0x430)
// WidgetBlueprintGeneratedClass W_MissionSelect.W_MissionSelect_C
class UW_MissionSelect_C : public UMissionSelectWidget
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x430(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                      AnimFadeIn;                                        // 0x438(0x8)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanel*                          ContentCanvas;                                     // 0x440(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScaleBox*                             DLCWarning;                                        // 0x448(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Image;                                             // 0x450(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Image_1;                                           // 0x458(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Image_2;                                           // 0x460(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Image_29;                                          // 0x468(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Image_36;                                          // 0x470(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Image_71;                                          // 0x478(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Img_LeftFade;                                      // 0x480(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Img_RightCornerFade;                               // 0x488(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                            Scroll_Levels;                                     // 0x490(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                  Txt_DLCWarning;                                    // 0x498(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                      Txt_ViewLevelLocation;                             // 0x4A0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                      Txt_ViewLevelName;                                 // 0x4A8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_DifficultySelect_C*                 W_DifficultySelect;                                // 0x4B0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_PageWrapper_C*                      W_PageWrapper;                                     // 0x4B8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FMargin                               LevelListPadding;                                  // 0x4C0(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	TArray<class UW_MissionSelect_Level_C*>      MissionWidgets;                                    // 0x4D0(0x10)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class UMissionSelectLevel*                   CurrentMission;                                    // 0x4E0(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UW_MissionSelect_Level_C*              LastMissionButton;                                 // 0x4E8(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UW_MissionSelect_EntryPoint_C*> EntryPointWidgets;                                 // 0x4F0(0x10)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class UW_MissionSelect_Level_C*              CurrentSelection;                                  // 0x500(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                         bUsingGamepad;                                     // 0x508(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_36BE[0x3];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	int32                                        CurrentNav;                                        // 0x50C(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         Increment_Option;                                  // 0x510(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class UW_MissionSelect_C* GetDefaultObj();

	void SequenceEvent__ENTRYPOINTW_MissionSelect(class UW_PageWrapper_C* W_PageWrapper);
	void OnMissionSelectAnimationStarted();
	void OnMissionSelectAnimationFinished();
	void DoCustomNavigation(enum class EUINavigation Navigation, bool K2Node_SwitchEnum_CmpSuccess, bool CallFunc_HandleNextInputAction_bPassthrough, bool CallFunc_IsValid_ReturnValue, bool CallFunc_HandlePreviousInputAction_bPassthrough);
	class UWidget* DifficultySelectToMissionListNavigate(enum class EUINavigation Navigation, class UWidget* CallFunc_Get_Focus_Target_Focus);
	class UWidget* MissionListToDifficultySelectNavigate(enum class EUINavigation Navigation);
	void Get_Focus_Target(class UWidget** Focus, bool CallFunc_IsValid_ReturnValue, class UWidget* CallFunc_GetChildAt_ReturnValue, class UW_MissionSelect_Level_C* K2Node_DynamicCast_AsW_Mission_Select_Level, bool K2Node_DynamicCast_bSuccess, class UWidget* CallFunc_GetFocusTarget_Focus, class UWidget* CallFunc_GetFocusTarget_Focus_1);
	void CloseNoCommanderModeNotice(class UW_StandardModal_C* CallingModal, class FText TextEntry);
	void NoCommanderModeNotice(class UMissionSelectCampaign* Campaign, enum class ECampaignLockReason Temp_byte_Variable, class FText Temp_text_Variable, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, class FText CallFunc_Format_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_2, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_3, class FText CallFunc_Format_ReturnValue_1, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array_2, class FText CallFunc_Format_ReturnValue_2, class FText K2Node_Select_Default);
	void GetCampaignByOptionID(class FName OptionID, bool* CampaignDataFound, class UMissionSelectCampaign** CampaignData, TArray<class UMissionSelectCampaign*>& CallFunc_GetCampaigns_ReturnValue, const class FString& CallFunc_Conv_NameToString_ReturnValue, int32 CallFunc_Conv_StringToInt_ReturnValue, bool CallFunc_Array_IsValidIndex_ReturnValue, class UMissionSelectCampaign* CallFunc_Array_Get_Item);
	void SetNavigation(const TArray<class FName>& Local_LockedArray, TMap<class FName, class FText> Local_OptionMap, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, const class FString& CallFunc_Conv_IntToString_ReturnValue, class FName CallFunc_Conv_StringToName_ReturnValue, int32 Temp_int_Array_Index_Variable_1, int32 CallFunc_Array_Length_ReturnValue, class FName CallFunc_Array_Get_Item, int32 Temp_int_Loop_Counter_Variable_1, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, TArray<class UMissionSelectCampaign*>& CallFunc_GetCampaigns_ReturnValue, class UMissionSelectCampaign* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1);
	void UpdateFooter(int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue);
	bool BP_OnHandleBackAction();
	void SetMissionDetails(class UMissionSelectLevel* LevelData, bool CallFunc_IsValid_ReturnValue);
	void PopulateLevelList(class UMissionSelectCampaign* Campaign, bool bIsLastWidget, class UW_MissionSelect_Level_C* NewLevelWidget, class UMissionSelectLevel* NewLevelData, int32 Temp_int_Array_Index_Variable, class UMissionSelectLevel* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, int32 CallFunc_Array_LastIndex_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, const struct FMargin& K2Node_MakeStruct_Margin, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_2, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_3, class UW_MissionSelect_Level_C* CallFunc_Create_ReturnValue, bool Temp_bool_Variable, const struct FMargin& K2Node_Select_Default, class UPanelSlot* CallFunc_AddChild_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_4, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_5, int32 CallFunc_Array_Add_ReturnValue);
	void OnMissionClicked(class UW_MissionSelect_Level_C* Button, class UMissionSelectLevel* LevelData, bool CallFunc_IsValid_ReturnValue, bool CallFunc_NotEqual_ObjectObject_ReturnValue);
	void SelectLevelButton(class UW_MissionSelect_Level_C* ButtonToSelect, int32 Temp_int_Array_Index_Variable, TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue, int32 Temp_int_Loop_Counter_Variable, class UWidget* CallFunc_Array_Get_Item, class UW_MissionSelect_Level_C* K2Node_DynamicCast_AsW_Mission_Select_Level, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_NotEqual_ObjectObject_ReturnValue);
	void GetDesiredMissionSelectButton(class UWidget** Widget, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UW_MissionSelect_Level_C* CallFunc_Array_Get_Item, bool CallFunc_Greater_IntInt_ReturnValue);
	class UWidget* EscapeMissionListNavigate(enum class EUINavigation Navigation, bool CallFunc_IsValid_ReturnValue);
	class UWidget* AcceptMissionNavigate(enum class EUINavigation Navigation, class UWidget* CallFunc_GetDesiredMissionSelectButton_Widget);
	class UWidget* BP_GetDesiredFocusTarget(bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsVisible_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UWidget* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class UW_MissionSelect_Level_C* K2Node_DynamicCast_AsW_Mission_Select_Level, bool K2Node_DynamicCast_bSuccess, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_GetIsFocusable_ReturnValue, bool CallFunc_IsVisible_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_2);
	void W_PageWrapper_Event_0(class UW_PageWrapper_C* W_PageWrapper);
	void Construct();
	void BP_OnActivated();
	void OnMissionHovered(class UW_MissionSelect_Level_C* Button);
	void ScrollToSelection(class UW_MissionSelect_Level_C* LevelButton);
	void BndEvt__W_MissionSelect_W_PageWrapper_K2Node_ComponentBoundEvent_3_OnFooterButtonClicked__DelegateSignature(const class FString& ButtonId);
	void AcceptMission(class FName SelectedEntryPoint);
	void BP_OnDeactivated();
	void BndEvt__W_MissionSelect_W_PageWrapper_K2Node_ComponentBoundEvent_1_OnNavOptionSelected__DelegateSignature(class FName OptionNameID);
	void Input_Changed(enum class ECommonInputType bNewInputType);
	void BndEvt__W_MissionSelect_W_PageWrapper_K2Node_ComponentBoundEvent_0_OnNavOptionPrevious__DelegateSignature(class FName Option_ID);
	void BndEvt__W_MissionSelect_W_PageWrapper_K2Node_ComponentBoundEvent_2_OnNavOptionNext__DelegateSignature(class FName Option_ID);
	void ExecuteUbergraph_W_MissionSelect(int32 EntryPoint, bool CallFunc_IsValid_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable, bool CallFunc_Not_PreBool_ReturnValue, class UW_PageWrapper_C* K2Node_CustomEvent_W_PageWrapper, class UUMGSequencePlayer* CallFunc_PlayAnimationForward_ReturnValue, class UW_MissionSelect_Level_C* K2Node_CustomEvent_Button, class UW_MissionSelect_Level_C* K2Node_CustomEvent_LevelButton, const class FString& K2Node_ComponentBoundEvent_ButtonID, bool K2Node_SwitchString_CmpSuccess, class FName K2Node_CustomEvent_SelectedEntryPoint, TArray<class UMissionSelectCampaign*>& CallFunc_GetCampaigns_ReturnValue, class FName K2Node_ComponentBoundEvent_OptionNameID, bool CallFunc_Array_IsValidIndex_ReturnValue, bool CallFunc_GetCampaignByOptionID_CampaignDataFound, class UMissionSelectCampaign* CallFunc_GetCampaignByOptionID_CampaignData, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, class FName CallFunc_Array_Get_Item, bool CallFunc_Array_IsValidIndex_ReturnValue_1, enum class EDescendantScrollDestination Temp_byte_Variable, enum class EDescendantScrollDestination Temp_byte_Variable_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, enum class ECommonInputType K2Node_CustomEvent_bNewInputType, bool Temp_bool_Variable, bool CallFunc_EqualEqual_ByteByte_ReturnValue, enum class EDescendantScrollDestination K2Node_Select_Default, class UWidget* CallFunc_Get_Focus_Target_Focus, bool CallFunc_IsValid_ReturnValue_2, class UWidget* CallFunc_GetChildAt_ReturnValue, TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue, class UW_MissionSelect_Level_C* K2Node_DynamicCast_AsW_Mission_Select_Level, bool K2Node_DynamicCast_bSuccess, class UWidget* CallFunc_Array_Get_Item_1, class UW_MissionSelect_Level_C* K2Node_DynamicCast_AsW_Mission_Select_Level_1, bool K2Node_DynamicCast_bSuccess_1, class UWidget* CallFunc_GetFocusTarget_Focus, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, class UCommonInputSubsystem* CallFunc_GetLocalPlayerSubsystem_ReturnValue, enum class ECommonInputType CallFunc_GetCurrentInputType_ReturnValue, class FName K2Node_ComponentBoundEvent_Option_ID_1, class FName K2Node_ComponentBoundEvent_Option_ID, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
};

}


