#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x370 (0x658 - 0x2E8)
// WidgetBlueprintGeneratedClass W_Stats_List.W_Stats_List_C
class UW_Stats_List_C : public UStatViewerWidget
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x2E8(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class UGridPanel*                            GP_Design;                                         // 0x2F0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UGridPanel*                            GP_StatList;                                       // 0x2F8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Img_div;                                           // 0x300(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                              LabelAndDifference;                                // 0x308(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                      Lbl_StatName;                                      // 0x310(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                      Txt_CompareDiff;                                   // 0x318(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                      Txt_Value;                                         // 0x320(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                      Txt_Value_Compare;                                 // 0x328(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                        RowCount;                                          // 0x330(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         bCompare;                                          // 0x334(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_3079[0x3];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TMap<class FString, class UCommonTextBlock*> ValueMap;                                          // 0x338(0x50)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TMap<class FString, class UCommonTextBlock*> DiffMap;                                           // 0x388(0x50)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TMap<class FString, class UCommonTextBlock*> LabelMap;                                          // 0x3D8(0x50)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TMap<class FString, class UCommonTextBlock*> CompareValueMap;                                   // 0x428(0x50)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	bool                                         Is_Design_Time;                                    // 0x478(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_307D[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	struct FFriend                               CompareFriend;                                     // 0x480(0x1C8)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UCommonTextBlock*>              TimeStats;                                         // 0x648(0x10)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)

	static class UClass* StaticClass();
	static class UW_Stats_List_C* GetDefaultObj();

	void GetFocusTarget(class UWidget** Focus);
	void BackPage(bool* Handled);
	void UpdateCompareValueEntry(const class FString& StatID, class UCommonTextBlock* UpdatedText, bool Temp_bool_Variable, class FText Temp_text_Variable, bool Temp_bool_Variable_1, bool Temp_bool_Variable_2, class FText Temp_text_Variable_1, bool Temp_bool_Variable_3, class UStatSubsystem* CallFunc_GetStatSubsystem_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, class UStatSubsystem* CallFunc_GetStatSubsystem_ReturnValue_1, class UStatSubsystem* CallFunc_GetStatSubsystem_ReturnValue_2, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsStatNumeric_ReturnValue, const class FString& CallFunc_GetFriendStatString_ReturnValue, class UCommonTextBlock* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, bool CallFunc_IsEmpty_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue, int64 CallFunc_GetFriendStatValue_ReturnValue, class FText K2Node_Select_Default, class FText CallFunc_Conv_Int64ToText_ReturnValue, class FText CallFunc_FormatPlaytime_Result, class FText K2Node_Select_Default_1, class FText K2Node_Select_Default_2, class FText K2Node_Select_Default_3);
	void FormatPlaytime(int64 Time__in_seconds_, class FText* Result, double CallFunc_Conv_Int64ToDouble_ReturnValue, const struct FTimespan& CallFunc_FromSeconds_ReturnValue, int32 CallFunc_BreakTimespan_Days, int32 CallFunc_BreakTimespan_Hours, int32 CallFunc_BreakTimespan_Minutes, int32 CallFunc_BreakTimespan_Seconds, int32 CallFunc_BreakTimespan_Milliseconds, int32 CallFunc_Multiply_IntInt_ReturnValue, int64 CallFunc_Conv_IntToInt64_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, int64 CallFunc_Conv_IntToInt64_ReturnValue_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Format_ReturnValue, float CallFunc_FromSeconds_Seconds_ImplicitCast);
	void UpdateValueEntry(const class FString& StatID, class UCommonTextBlock* UpdatedText, bool Temp_bool_Variable, class FText Temp_text_Variable, bool Temp_bool_Variable_1, bool Temp_bool_Variable_2, class FText Temp_text_Variable_1, bool Temp_bool_Variable_3, class UStatSubsystem* CallFunc_GetStatSubsystem_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, class UStatSubsystem* CallFunc_GetStatSubsystem_ReturnValue_1, class UStatSubsystem* CallFunc_GetStatSubsystem_ReturnValue_2, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsStatNumeric_ReturnValue, int64 CallFunc_GetStatValue_ReturnValue, class UCommonTextBlock* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, class FText CallFunc_Conv_Int64ToText_ReturnValue, class FText CallFunc_FormatPlaytime_Result, const class FString& CallFunc_GetStatString_ReturnValue, class FText K2Node_Select_Default, bool CallFunc_IsEmpty_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue, class FText K2Node_Select_Default_1, class FText K2Node_Select_Default_2, class FText K2Node_Select_Default_3);
	void CompareStats(int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<class FString>& CallFunc_Map_Keys_Keys, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
	void CreateComparisonValueEntry(const struct FDataTableRowHandle& StatRowHandle, int32 InRow, int32 InColumn, class UCommonTextBlock** ValueTextWidget, bool IsTime, const class FString& StatID, class UCommonTextBlock* NewComparisonValueText, const class FString& Temp_string_Variable, const struct FStatDefinition& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, bool CallFunc_IsValid_ReturnValue, enum class ERONStatType Temp_wildcard_Variable, bool Temp_bool_Variable, bool Temp_bool_Variable_1, class FText Temp_text_Variable, const class FString& Temp_string_Variable_1, class FText Temp_text_Variable_1, int64 Temp_int64_Variable, bool Temp_bool_Variable_2, const struct FMargin& K2Node_MakeStruct_Margin, bool Temp_bool_Variable_3, bool Temp_bool_Variable_4, bool Temp_bool_Variable_5, class FText Temp_text_Variable_2, bool Temp_bool_Variable_6, uint8 CallFunc_MakeLiteralByte_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, int64 CallFunc_RandomInteger64InRange_ReturnValue, class FText CallFunc_Conv_Int64ToText_ReturnValue, class FText CallFunc_FormatPlaytime_Result, class FText K2Node_Select_Default, class UGridSlot* CallFunc_AddChildToGrid_ReturnValue, class FText K2Node_Select_Default_1, class UStatSubsystem* CallFunc_GetStatSubsystem_ReturnValue, class UStatSubsystem* CallFunc_GetStatSubsystem_ReturnValue_1, class UStatSubsystem* CallFunc_GetStatSubsystem_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, class UCommonTextBlock* CallFunc_CopyTextObject_NewCommonTextBlock, bool CallFunc_IsStatNumeric_ReturnValue, int64 CallFunc_GetFriendStatValue_ReturnValue, const class FString& CallFunc_GetFriendStatString_ReturnValue, class FText CallFunc_Conv_Int64ToText_ReturnValue_1, bool CallFunc_IsEmpty_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue, class FText CallFunc_FormatPlaytime_Result_1, class FText K2Node_Select_Default_2, class FText K2Node_Select_Default_3, class FText K2Node_Select_Default_4, class FText K2Node_Select_Default_5);
	void AddDiv(int32 Temp_int_Variable, int32 Temp_int_Variable_1, class UImage* CallFunc_SpawnObject_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, const struct FMargin& K2Node_MakeStruct_Margin, class UGridSlot* CallFunc_AddChildToGrid_ReturnValue);
	void CopyTextObject(class UCommonTextBlock* CommonTextToCopy, class UCommonTextBlock** NewCommonTextBlock, class UCommonTextBlock* CallFunc_SpawnObject_ReturnValue);
	void CreateLabel(const struct FDataTableRowHandle& StatRowHandle, int32 Row, int32 Column, class UOverlay** LabelOverlay, class FText DisplayName, const class FString& StatID, class UCommonTextBlock* NewDiffText, class UOverlay* NewLabelOverlay, class UCommonTextBlock* NewStatLabel, enum class ERONStatType Temp_wildcard_Variable, const class FString& Temp_string_Variable, const struct FStatDefinition& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, bool CallFunc_IsValid_ReturnValue, class FText Temp_text_Variable, const class FString& Temp_string_Variable_1, uint8 CallFunc_MakeLiteralByte_ReturnValue, int64 Temp_int64_Variable, class UOverlay* CallFunc_SpawnObject_ReturnValue, enum class EHorizontalAlignment Temp_byte_Variable, bool Temp_bool_Variable, enum class EHorizontalAlignment Temp_byte_Variable_1, bool Temp_bool_Variable_1, class UGridSlot* CallFunc_AddChildToGrid_ReturnValue, enum class EHorizontalAlignment K2Node_Select_Default, class UOverlaySlot* CallFunc_AddChildToOverlay_ReturnValue, class UCommonTextBlock* CallFunc_CopyTextObject_NewCommonTextBlock, class UOverlaySlot* CallFunc_AddChildToOverlay_ReturnValue_1, class UCommonTextBlock* CallFunc_CopyTextObject_NewCommonTextBlock_1);
	void CreateValueEntry(const struct FDataTableRowHandle& StatRowHandle, int32 InRow, int32 InColumn, class UCommonTextBlock** ValueTextWidget, bool IsTime, int64 DebugValue, const class FString& DebugString, enum class ERONStatType StatType, const class FString& StatID, class UCommonTextBlock* NewValueText, const class FString& Temp_string_Variable, const struct FStatDefinition& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, bool CallFunc_IsValid_ReturnValue, enum class ERONStatType Temp_wildcard_Variable, bool Temp_bool_Variable, bool Temp_bool_Variable_1, enum class ERONStatType Temp_byte_Variable, class FText Temp_text_Variable, const class FString& Temp_string_Variable_1, const struct FMargin& K2Node_MakeStruct_Margin, bool Temp_bool_Variable_2, int64 Temp_int64_Variable, bool Temp_bool_Variable_3, bool Temp_bool_Variable_4, bool Temp_bool_Variable_5, bool Temp_bool_Variable_6, class FText Temp_text_Variable_1, bool Temp_bool_Variable_7, uint8 CallFunc_MakeLiteralByte_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, int64 CallFunc_RandomInteger64InRange_ReturnValue, class FText CallFunc_Conv_Int64ToText_ReturnValue, class FText CallFunc_FormatPlaytime_Result, class FText K2Node_Select_Default, class UStatSubsystem* CallFunc_GetStatSubsystem_ReturnValue, class UStatSubsystem* CallFunc_GetStatSubsystem_ReturnValue_1, class UStatSubsystem* CallFunc_GetStatSubsystem_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_1, class UGridSlot* CallFunc_AddChildToGrid_ReturnValue, class FText CallFunc_Conv_Int64ToText_ReturnValue_1, class FText CallFunc_FormatPlaytime_Result_1, class FText K2Node_Select_Default_1, class FText CallFunc_Conv_StringToText_ReturnValue, class FText K2Node_Select_Default_2, class FText K2Node_Select_Default_3, bool CallFunc_IsStatNumeric_ReturnValue, int64 CallFunc_GetStatValue_ReturnValue, class FText CallFunc_Conv_Int64ToText_ReturnValue_2, class FText CallFunc_FormatPlaytime_Result_2, const class FString& CallFunc_GetStatString_ReturnValue, class FText K2Node_Select_Default_4, bool CallFunc_IsEmpty_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue_1, class FText K2Node_Select_Default_5, class FText K2Node_Select_Default_6, class UCommonTextBlock* CallFunc_CopyTextObject_NewCommonTextBlock, class FText K2Node_Select_Default_7);
	void PopulateStats(const struct FDataTableRowHandle& StatRow, const class FString& CurrentStatID, int32 ColumnCount, enum class ESlateVisibility Temp_byte_Variable, enum class ESlateVisibility Temp_byte_Variable_1, bool Temp_bool_Variable, int32 Temp_int_Array_Index_Variable, class UCommonTextBlock* CallFunc_CreateComparisonValueEntry_ValueTextWidget, enum class ESlateVisibility K2Node_Select_Default, class UOverlay* CallFunc_CreateLabel_LabelOverlay, int32 Temp_int_Loop_Counter_Variable, class UCommonTextBlock* CallFunc_CreateValueEntry_ValueTextWidget, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, const struct FDataTableRowHandle& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_Array_IsValidIndex_ReturnValue);
	void Reveal(double Delay);
	void Hide(double Delay, bool Collapse);
	void SetInputMode(bool IsGamepad);
	void ChangePage(class FName PageName);
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void StatsLoaded();
	void OnInitialized();
	void OnStatChanged(const class FString& StatID);
	void CompareWithFriend(const struct FFriend& Friend);
	void CancelCompare();
	void ExecuteUbergraph_W_Stats_List(int32 EntryPoint, double K2Node_Event_Delay_1, double K2Node_Event_Delay, bool K2Node_Event_Collapse, bool K2Node_Event_IsGamepad, class FName K2Node_Event_PageName, bool K2Node_Event_IsDesignTime, class UStatSubsystem* CallFunc_GetGameInstanceSubsystem_ReturnValue, bool CallFunc_IsValid_ReturnValue, const class FString& K2Node_Event_StatID, const struct FFriend& K2Node_Event_Friend, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class UStatSubsystem* CallFunc_GetStatSubsystem_ReturnValue, bool CallFunc_IsInitialized_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
};

}


