#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x1F8 (0x690 - 0x498)
// WidgetBlueprintGeneratedClass W_WeaponWheel.W_WeaponWheel_C
class UW_WeaponWheel_C : public UWeaponWheelWidget
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x498(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class UBackgroundBlur*                       BackgroundBlur;                                    // 0x4A0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                        Controls_Container;                                // 0x4A8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_DebugInfoContainer_C*               DebugInfoContainer_Items;                          // 0x4B0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_DebugInfoContainer_C*               DebugInfoContainer_Logic;                          // 0x4B8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_DebugInfoContainer_C*               DebugInfoContainer_Settings;                       // 0x4C0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                Image_250;                                         // 0x4C8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                              TestSmoothCursor;                                  // 0x4D0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                            WeaponStat_Category_Text;                          // 0x4D8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                            WeaponStat_ItemName_Text;                          // 0x4E0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                WeaponWheel_Background;                            // 0x4E8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                WeaponWheel_InnerBorder;                           // 0x4F0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                          WeaponWheel_ItemInfo_Container;                    // 0x4F8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                          WeaponWheel_ItemStats_Container;                   // 0x500(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_WeaponWheel_MultiItem_Selection_C*  WeaponWheel_MultiItem_Selection;                   // 0x508(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                WeaponWheel_OuterBorder;                           // 0x510(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                          WeaponWheelArea;                                   // 0x518(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMap<class FName, class UW_WeaponWheel_RadialSelection_C*> WheelCategoryToRadialSelectionWidget;              // 0x520(0x50)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TArray<class UW_WeaponWheel_ItemStat_C*>     ItemStats;                                         // 0x570(0x10)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TArray<class UW_WeaponWheel_RadialSelection_C*> WeaponWheelCategories;                             // 0x580(0x10)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TArray<class ABaseItem*>                     ItemCategories;                                    // 0x590(0x10)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	enum class EEasingFunc                       StatGrowthEffect;                                  // 0x5A0(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                        Pad_3718[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	double                                       StatGrowthSpeed;                                   // 0x5A8(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	int32                                        CategoryTextFontSize;                              // 0x5B0(0x4)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	int32                                        ItemTextFontSize;                                  // 0x5B4(0x4)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TArray<class ABaseItem*>                     Primary_Weapons;                                   // 0x5B8(0x10)(Edit, BlueprintVisible, DisableEditOnTemplate, ExposeOnSpawn)
	TArray<class ABaseItem*>                     Secondary_Weapons;                                 // 0x5C8(0x10)(Edit, BlueprintVisible, DisableEditOnTemplate, ExposeOnSpawn)
	TArray<class ABaseItem*>                     Grenades;                                          // 0x5D8(0x10)(Edit, BlueprintVisible, DisableEditOnTemplate, ExposeOnSpawn)
	TArray<class ABaseItem*>                     Assistants;                                        // 0x5E8(0x10)(Edit, BlueprintVisible, DisableEditOnTemplate, ExposeOnSpawn)
	TArray<class ABaseItem*>                     Tactical_Devices;                                  // 0x5F8(0x10)(Edit, BlueprintVisible, DisableEditOnTemplate, ExposeOnSpawn)
	TArray<class ABaseItem*>                     TabletDevices;                                     // 0x608(0x10)(Edit, BlueprintVisible, DisableEditOnTemplate, ExposeOnSpawn)
	class UW_WeaponWheel_RadialSelection_C*      CurrentSelectedRadialWidget;                       // 0x618(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UW_WeaponWheel_RadialSelection_C*      PreviousSelectedRadialWidget;                      // 0x620(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_            CategoryDeselected;                                // 0x628(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_            CategorySelected;                                  // 0x638(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_            ItemSelected;                                      // 0x648(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_            ItemDeselected;                                    // 0x658(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	int32                                        MaxItemStats;                                      // 0x668(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_372D[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TArray<class UClass*>                        ItemExecutables;                                   // 0x670(0x10)(Edit, BlueprintVisible, ExposeOnSpawn)
	TArray<class UWeaponWheelScript*>            ItemExecutableScripts;                             // 0x680(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)

	static class UClass* StaticClass();
	static class UW_WeaponWheel_C* GetDefaultObj();

	bool RemoveNullItemsFromAllCategories(bool CallFunc_RemoveNullItemsFromAllCategories_ReturnValue);
	bool RemoveNullItemsFromCategory(class FName& WeaponWheelCategoryName, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void IsItemAtBack(class ABaseItem* Item, bool* Return_Value, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_IsItemAtIndex_Return_Value);
	void IsItemAtFront(class ABaseItem* Item, bool* Return_Value, bool CallFunc_IsItemAtIndex_Return_Value);
	void IsItemAtIndex(class ABaseItem* Item, int32 Index, bool* Return_Value, bool Temp_bool_True_if_break_was_hit_Variable, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 Temp_int_Array_Index_Variable, bool CallFunc_EqualEqual_IntInt_ReturnValue, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UObject* CallFunc_Array_Get_Item, class ABaseItem* K2Node_DynamicCast_AsBase_Item, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1);
	void ClearStats();
	void UpdateDebugInformation(class FText CallFunc_Conv_DoubleToText_ReturnValue, class UW_DebugInfo_C* CallFunc_Get_Debug_Item__Index__DebugInfoWidget, class FText CallFunc_Conv_DoubleToText_ReturnValue_1, class UW_DebugInfo_C* CallFunc_Get_Debug_Item__Index__DebugInfoWidget_1, class FText CallFunc_Conv_DoubleToText_ReturnValue_2, class UW_DebugInfo_C* CallFunc_Get_Debug_Item__Index__DebugInfoWidget_2, class FText CallFunc_Conv_DoubleToText_ReturnValue_3, class UW_DebugInfo_C* CallFunc_Get_Debug_Item__Index__DebugInfoWidget_3, class FText CallFunc_Conv_DoubleToText_ReturnValue_4, class UW_DebugInfo_C* CallFunc_Get_Debug_Item__Index__DebugInfoWidget_4, class FText CallFunc_Conv_DoubleToText_ReturnValue_5, class UW_DebugInfo_C* CallFunc_Get_Debug_Item__Index__DebugInfoWidget_5, bool CallFunc_IsValid_ReturnValue, class FText CallFunc_Conv_NameToText_ReturnValue, class UW_DebugInfo_C* CallFunc_Get_Debug_Item__Index__DebugInfoWidget_6, float CallFunc_GetCorrectAngle_ReturnValue, class FText CallFunc_Conv_DoubleToText_ReturnValue_6, class UW_DebugInfo_C* CallFunc_Get_Debug_Item__Index__DebugInfoWidget_7, float CallFunc_GetRenderTransformAngle_ReturnValue, class FText CallFunc_Conv_DoubleToText_ReturnValue_7, class UW_DebugInfo_C* CallFunc_Get_Debug_Item__Index__DebugInfoWidget_8, class UW_DebugInfo_C* CallFunc_Get_Debug_Item__Index__DebugInfoWidget_9, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_2, class FText CallFunc_Conv_IntToText_ReturnValue, class FText CallFunc_Conv_IntToText_ReturnValue_1, class UW_DebugInfo_C* CallFunc_Get_Debug_Item__Index__DebugInfoWidget_10, int32 CallFunc_Array_Length_ReturnValue_3, class FText CallFunc_Conv_IntToText_ReturnValue_2, class UW_DebugInfo_C* CallFunc_Get_Debug_Item__Index__DebugInfoWidget_11, class FText CallFunc_Conv_IntToText_ReturnValue_3, class UW_DebugInfo_C* CallFunc_Get_Debug_Item__Index__DebugInfoWidget_12, class FText CallFunc_Conv_IntToText_ReturnValue_4, class UW_DebugInfo_C* CallFunc_Get_Debug_Item__Index__DebugInfoWidget_13, double CallFunc_Conv_DoubleToText_Value_ImplicitCast, double CallFunc_Conv_DoubleToText_Value_ImplicitCast_1, double CallFunc_Conv_DoubleToText_Value_ImplicitCast_2, double CallFunc_Conv_DoubleToText_Value_ImplicitCast_3, double CallFunc_Conv_DoubleToText_Value_ImplicitCast_4, double CallFunc_Conv_DoubleToText_Value_ImplicitCast_5, double CallFunc_Conv_DoubleToText_Value_ImplicitCast_6, double CallFunc_Conv_DoubleToText_Value_ImplicitCast_7);
	void RemoveExecutableItemFromCategory(class UClass* NewWeaponWheelScript, int32 AtIndex, class UWeaponWheelScript* CallFunc_Array_Get_Item, const class FString& CallFunc_Conv_TextToString_ReturnValue, class FName CallFunc_Conv_StringToName_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void AddExecutableItemToCategory(class UClass* NewWeaponWheelScript, int32 AtIndex, bool Temp_bool_True_if_break_was_hit_Variable, const class FString& CallFunc_Conv_TextToString_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, class FName CallFunc_Conv_StringToName_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, class UWeaponWheelScript* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, class UClass* CallFunc_GetObjectClass_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_ClassClass_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, class UWeaponWheelScript* CallFunc_SpawnObject_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, const class FString& CallFunc_Conv_TextToString_ReturnValue_1, class FName CallFunc_Conv_StringToName_ReturnValue_1, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void ShuffleItemsInCategory(class FName CategoryName, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void GetCurrentICategorytemCount(int32* Return_Value, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Array_Length_ReturnValue);
	void GetCurrentItemSelectionIndex(int32* Return_Value, bool CallFunc_IsValid_ReturnValue);
	void MoveItemToAnotherCategory__Index_(int32 ItemIndex, class FName FromCategory, class FName ToCategory, int32 NewIndexInCategory, class ABaseItem* SavedItem, const class FString& CallFunc_Conv_NameToString_ReturnValue, const class FString& CallFunc_Conv_NameToString_ReturnValue_1, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Conv_NameToString_ReturnValue_2, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, const class FString& CallFunc_Concat_StrStr_ReturnValue_2, const class FString& CallFunc_Concat_StrStr_ReturnValue_3, int32 CallFunc_Array_Find_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, class UW_WeaponWheel_RadialSelection_C* CallFunc_Array_Get_Item, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, class ABaseItem* CallFunc_Array_Get_Item_1, bool CallFunc_Array_Contains_ReturnValue, const class FString& CallFunc_Conv_TextToString_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_4, const class FString& CallFunc_Concat_StrStr_ReturnValue_5, const class FString& CallFunc_Concat_StrStr_ReturnValue_6, const class FString& CallFunc_Concat_StrStr_ReturnValue_7);
	void MoveItemToAnotherCategory(class ABaseItem* Item, class FName ToCategory, int32 NewIndexInCategory, const class FString& CallFunc_Conv_NameToString_ReturnValue, const class FString& CallFunc_Conv_NameToString_ReturnValue_1, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, const class FString& CallFunc_Conv_TextToString_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_2, const class FString& CallFunc_Concat_StrStr_ReturnValue_3, const class FString& CallFunc_Conv_NameToString_ReturnValue_2, const class FString& CallFunc_Concat_StrStr_ReturnValue_4, const class FString& CallFunc_Concat_StrStr_ReturnValue_5, const class FString& CallFunc_Concat_StrStr_ReturnValue_6, const class FString& CallFunc_Concat_StrStr_ReturnValue_7, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1, bool CallFunc_Array_Contains_ReturnValue);
	void MoveItemToNewSpot__Index_(int32 ItemIndex, class FName CategoryName, int32 NewIndex, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, class ABaseItem* CallFunc_Array_Get_Item);
	void MoveItemToNewSpot(class ABaseItem* Item, int32 NewIndex, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void MoveItemToBack(class ABaseItem* Item, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void MoveItemToFront(class ABaseItem* Item, bool CallFunc_IsValid_ReturnValue, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void MoveItemToBack__Index_(int32 ItemIndex, class FName CategoryName, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, class ABaseItem* CallFunc_Array_Get_Item);
	void MoveItemToFront__Index_(int32 ItemIndex, class FName CategoryName, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, class ABaseItem* CallFunc_Array_Get_Item);
	void RemoveAssistant(class ABaseItem* AssistantItem);
	void RemoveTabletDevice(class ABaseItem* TabletDeviceItem);
	void RemoveTactical_Devices(class ABaseItem* DoorDeviceItem);
	void RemoveGrenade(class ABaseItem* GrenadeItem);
	void RemoveSecondaryWeapon(class ABaseItem* SecondaryWeaponItem);
	void RemovePrimaryWeapon(class ABaseItem* PrimaryWeaponItem);
	void RemoveItemFromCategory(class ABaseItem*& Item, class FName Wheel_Category, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void AddItemToCategory(class ABaseItem*& Item, class FName Wheel_Category, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void AddTabletDevice(class ABaseItem*& TabletDevice_Item);
	void AddTactical_Device(class ABaseItem*& Tactical_Device_Item);
	void AddAssistants(class ABaseItem*& Assistants);
	void AddGrenade(class ABaseItem*& GrenadeItem);
	void AddSecondaryWeapon(class ABaseItem*& SecondayWeaponItem);
	void AddPrimaryWeapon(class ABaseItem* PrimaryWeaponItem);
	void RefreshMultiItemWidget(int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue);
	bool IsWheelCursorVisible(bool CallFunc_IsVisible_ReturnValue);
	bool OnRadialMenuInitialized(double CallFunc_MapRangeClamped_ReturnValue, const struct FVector2D& CallFunc_MakeVector2D_ReturnValue, bool CallFunc_OnRadialMenuInitialized_ReturnValue, double CallFunc_MapRangeClamped_InRangeB_ImplicitCast, double CallFunc_MapRangeClamped_Value_ImplicitCast);
	bool OnRadialSectorCreated(int32 Index, float InAngle, bool CallFunc_OnRadialSectorCreated_ReturnValue, class UCanvasPanelSlot* CallFunc_CreateWheelCategory_Canvas_Panel_Slot, const struct FVector2D& CallFunc_MakeVector2D_ReturnValue, class UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue, const struct FVector2D& CallFunc_GetPosition_ReturnValue, const struct FVector2D& CallFunc_CalculatePositionOnCircleFromWidget_ReturnValue, double CallFunc_MakeVector2D_X_ImplicitCast, double CallFunc_MakeVector2D_Y_ImplicitCast);
	bool ExecuteRadial(bool CallFunc_ExecuteRadial_ReturnValue);
	bool ShowWheel();
	bool HideWheel();
	void NotifyAllStatsOnWheelCreated(int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UW_WeaponWheel_ItemStat_C* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void NotifyAllCategoriesOnWheelCreated(int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UW_WeaponWheel_RadialSelection_C* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue);
	void FindDataTableRowNameFromItemName(class FName ItemName, class FName* RowName);
	void StatEnumToName(uint8 Item_Stat, class FName* Stat_Name, bool K2Node_SwitchEnum_CmpSuccess);
	void RefreshStats(TArray<class UClass*>& ItemStats, const struct FItemLookupTable& ItemDataTable, bool Temp_bool_True_if_break_was_hit_Variable, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 Temp_int_Variable, class UClass* CallFunc_Array_Get_Item, class UClass* K2Node_ClassDynamicCast_AsW_Weapon_Wheel_Item_Stat, bool K2Node_ClassDynamicCast_bSuccess, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, bool Temp_bool_Variable, bool CallFunc_Not_PreBool_ReturnValue_1, class UW_WeaponWheel_ItemStat_C* CallFunc_CreateWheelStat_ItemStatWidget, class UW_WeaponWheel_ItemStat_C* CallFunc_Array_Get_Item_1, int32 CallFunc_Clamp_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1);
	void RefreshCategory(TArray<class ABaseItem*>& New_Category_Items, TArray<class UWeaponWheelScript*>& NewWeaponWheelScripts, class FName Category_Name, int32 StartingItemIndex, int32 CallFunc_Array_Find_ReturnValue, class UW_WeaponWheel_RadialSelection_C* CallFunc_Array_Get_Item, int32 CallFunc_Array_Find_ReturnValue_1, class UW_WeaponWheel_RadialSelection_C* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue, class UW_WeaponWheel_RadialSelection_C* CallFunc_Array_Get_Item_2, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue);
	void UpdateTabletDevices(TArray<class ABaseItem*>& NewTabletDevices, int32 StartingItemIndex, class FName Temp_name_Variable, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void UpdateTacticalDevices(TArray<class ABaseItem*>& NewDoorDevices, int32 StartingItemIndex, class FName Temp_name_Variable, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void UpdateAssistants(TArray<class ABaseItem*>& NewAssistants, int32 StartingItemIndex, class FName Temp_name_Variable, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void UpdateGrenades(TArray<class ABaseItem*>& NewGrenades, int32 StartingItemIndex, class FName Temp_name_Variable, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void UpdateSecondaryWeapons(TArray<class ABaseItem*>& NewSecondaryWeapons, int32 StartingItemIndex, class FName Temp_name_Variable, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void UpdatePrimaryWeapons(TArray<class ABaseItem*>& New_Primary_Weapons, int32 StartingItemIndex, class FName Temp_name_Variable, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void PreviousItem(bool CallFunc_IsValid_ReturnValue, bool CallFunc_PreviousItem_bSuccess, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_Previous_bSuccess);
	void NextItem(bool CallFunc_IsValid_ReturnValue, bool CallFunc_NextItem_bSuccess, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_Next_bSuccess);
	void PopulateAllCategories(int32 Temp_int_Array_Index_Variable, class UClass* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
	void PopulateCategory(TArray<class ABaseItem*>& Items, class FName Category_Name_, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, class ABaseItem* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, class UW_WeaponWheel_RadialSelection_C* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void PlaceWidgetInWheel(class UCanvasPanelSlot*& Canvas_Slot, const struct FVector2D& Positionn);
	void SelectItem(class UW_WeaponWheel_RadialSelection_C* ItemToSelect, bool Play_Animation, bool Play_Sound, bool Refresh_Stats, bool* bSuccess, bool CallFunc_IsInExecutablesArray_Return_Value, class FName CallFunc_GetItemName_Item_Name, class FText CallFunc_GetCategory_Category, class FText CallFunc_Conv_NameToText_ReturnValue, bool CallFunc_IsValid_ReturnValue, const struct FLinearColor& CallFunc_GetCorrectSelectionColor_ReturnValue);
	void CreateWheelStat(class UClass* ItemStatClass, double FillSpeed, enum class EEasingFunc EasingFunction, const struct FItemLookupTable& LookupTable, class UW_WeaponWheel_ItemStat_C** ItemStatWidget, double CallFunc_MapRangeClamped_ReturnValue, double CallFunc_MapRangeClamped_ReturnValue_1, const struct FVector2D& CallFunc_MakeVector2D_ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class UW_WeaponWheel_ItemStat_C* CallFunc_Create_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, class UVerticalBoxSlot* CallFunc_AddChildToVerticalBox_ReturnValue, double CallFunc_SetDoublePropertyByName_Value_ImplicitCast, double CallFunc_MapRangeClamped_InRangeB_ImplicitCast, double CallFunc_MapRangeClamped_Value_ImplicitCast, double CallFunc_MapRangeClamped_InRangeB_ImplicitCast_1, double CallFunc_MapRangeClamped_Value_ImplicitCast_1, double CallFunc_SetDoublePropertyByName_Value_ImplicitCast_1);
	void CreateWheelCategory(int32 Index, class FName Category_Name, class UCanvasPanelSlot** Canvas_Panel_Slot, class FText CallFunc_Conv_NameToText_ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class ABaseItem* CallFunc_Array_Get_Item, class UW_WeaponWheel_RadialSelection_C* CallFunc_Create_ReturnValue, class UCanvasPanelSlot* CallFunc_AddChildToCanvas_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, class UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue, const struct FAnchors& CallFunc_GetAnchors_ReturnValue, double CallFunc_SetDoublePropertyByName_Value_ImplicitCast, double CallFunc_SetDoublePropertyByName_Value_ImplicitCast_1, double CallFunc_SetDoublePropertyByName_Value_ImplicitCast_2);
	void Construct();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void OnItemSelcted(bool Play_Animation);
	void OnItemDeselected();
	void OnSectorSelected(int32 SelectedIndex);
	void OnSectorDeselected(int32 DeselectedIndex);
	void OnRadialMenuCreated();
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_W_WeaponWheel(int32 EntryPoint, bool CallFunc_Greater_DoubleDouble_ReturnValue, bool CallFunc_Less_DoubleDouble_ReturnValue, const struct FGeometry& K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime, bool K2Node_CustomEvent_Play_Animation, bool CallFunc_SelectItem_bSuccess, bool CallFunc_SelectItem_bSuccess_1, class FName CallFunc_GetItemName_Item_Name, class FName CallFunc_GetItemName_Item_Name_1, class UCanvasPanelSlot* CallFunc_SlotAsCanvasSlot_ReturnValue, class UMaterialInstanceDynamic* CallFunc_GetDynamicMaterial_ReturnValue, class ABaseItem* CallFunc_Array_Get_Item, class ABaseItem* CallFunc_Array_Get_Item_1, class ABaseItem* CallFunc_Array_Get_Item_2, class ABaseItem* CallFunc_Array_Get_Item_3, class ABaseItem* CallFunc_Array_Get_Item_4, class ABaseItem* CallFunc_Array_Get_Item_5, TArray<class ABaseItem*>& K2Node_MakeArray_Array, double CallFunc_Conv_IntToDouble_ReturnValue, int32 K2Node_Event_SelectedIndex, double CallFunc_Conv_IntToDouble_ReturnValue_1, class UW_WeaponWheel_RadialSelection_C* CallFunc_Array_Get_Item_6, int32 K2Node_Event_DeselectedIndex, class UW_WeaponWheel_RadialSelection_C* CallFunc_Array_Get_Item_7, const struct FVector2D& CallFunc_MakeVector2D_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue_1, double CallFunc_Add_DoubleDouble_ReturnValue, double CallFunc_MapRangeClamped_ReturnValue, int32 CallFunc_FTrunc_ReturnValue, double CallFunc_MapRangeClamped_ReturnValue_1, double CallFunc_Conv_IntToDouble_ReturnValue_2, int32 CallFunc_FTrunc_ReturnValue_1, double CallFunc_Conv_IntToDouble_ReturnValue_3, const struct FVector2D& CallFunc_GetCenterScreenPosition_ReturnValue, bool K2Node_Event_IsDesignTime, enum class ERONBuildConfiguration CallFunc_GetBuildConfiguration_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess, const struct FSlateFontInfo& K2Node_MakeStruct_SlateFontInfo, const struct FSlateFontInfo& K2Node_MakeStruct_SlateFontInfo_1, double CallFunc_Greater_DoubleDouble_A_ImplicitCast, double CallFunc_Less_DoubleDouble_A_ImplicitCast, double CallFunc_MakeVector2D_X_ImplicitCast, double CallFunc_MakeVector2D_Y_ImplicitCast, double CallFunc_Subtract_DoubleDouble_B_ImplicitCast, double CallFunc_Subtract_DoubleDouble_B_ImplicitCast_1, float K2Node_VariableSet_GamepadAngle_ImplicitCast, double CallFunc_Add_DoubleDouble_A_ImplicitCast, float CallFunc_SetScalarParameterValue_Value_ImplicitCast, double CallFunc_MapRangeClamped_Value_ImplicitCast, double CallFunc_MapRangeClamped_InRangeB_ImplicitCast, double CallFunc_MapRangeClamped_Value_ImplicitCast_1, double CallFunc_MapRangeClamped_InRangeB_ImplicitCast_1, float K2Node_MakeStruct_Size_ImplicitCast, float K2Node_MakeStruct_Size_ImplicitCast_1);
	void ItemDeselected__DelegateSignature(int32 Category_Index, class FName Category_Name, int32 Item_Index, class FName Item_Name);
	void ItemSelected__DelegateSignature(int32 Category_Index, class FName Category_Name, int32 Item_Index, class FName Item_Name);
	void CategorySelected__DelegateSignature(int32 Category_Index, class FName Category_Name);
	void CategoryDeselected__DelegateSignature(int32 Category_Index, class FName Category_Name);
};

}


